hydra:
  job_logging:
    root:
      handlers: [file, console]  # logging to file only.
  run:
    dir: ./

# Fixed setting
data_dir: dataset
save_dir: ckpt
log_dir: performance
n_classes : 2 # Changes automatically.
num_workers: 4
model_name_or_path: bert-base-uncased
num_layer: 12 # changes automatically. !!
max_seq_length: 512
device: 0
n_gpu: 1

# Basic config
model_name: "LaCL"
num_train_epochs: 40
train_batch: 100
seed: 1
log_interval: 1

# Experiment type (split/non-split)
split: True
split_ratio: 0.5 # [0.25, 0.5, 0.75]
task_name: banking77 # ['clinc150', 'snips', 'banking77', 'mix_snips', 'mix_banking']

# Optimizer & Scheduler
learning_rate: 1e-5 # Adamw : [1e-5, 5e-6]
eta_min: 5e-2
weight_decay: 0.01
adam_epsilon: 1e-6

# Data augmentation
augment_both: "span"
augment_method: "bt/span"
no_dropout: False
dataset_num: 1
beam: 1
ss_ratio: 0.1
cw_ratio: 0.1
second_aug_ratio: 0.5
permutation: False
span_mask_len: 5
cutoff_ratio: 0.15


# LaCL config
gp_location: 'token'
gp_pooling: concat
gp_layers: [1,2,3,4,5,6,7,8,9,10,11,12] # global projector layers

cosine_top_k: 1
reg_loss_weight: 0.1 
encoder_dim: 1024 # 1024(encoder dimension)-> 128(projection dimension) in Contrastive learning
projection_dim: 768 # projection dimension in Contrastive learning and hidden dim in Vanilla PLM classification.
temperature: 0.05


